name: birthy
description: Never miss wishing a birthday again!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.0
  flutter_local_notifications: ^14.1.0
  cupertino_icons: ^1.0.5
  uuid: ^3.0.6
  timezone: ^0.9.1
  numberpicker: ^2.1.1
  flutter_lints: ^4.0.0
dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  uses-material-design: true
  fonts:
    - family: NotoSans # Use the actual font family name from Google Fonts
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf # Update with the correct font file name
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf # Update with the correct font file name
          weight: 700
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  flutter_test:
    sdk: flutter

